/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: visualboy (https://sketchfab.com/visualboy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/opera-one-spiral-cubes-b24db8ba9d7e4fbf85c90f866ee21bb0
Title: Opera One - Spiral Cubes
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/3D/opera_one_-_spiral_cubes.glb')
  const { actions } = useAnimations(animations, group)

  // Activar todas las animaciones cuando el componente se monte
  useEffect(() => {
    console.log('Animaciones disponibles:', Object.keys(actions))
    
    // Reproducir todas las animaciones
    Object.values(actions).forEach((action) => {
      action?.play()
    })
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="42fc354ac4ff4650bd4277fa4068c8ecfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Cube_helix_02" rotation={[Math.PI, 0, -Math.PI]}>
                  <group name="Cloner">
                    <group name="Cube_0" position={[5, 0, 0]} rotation={[1.011, 0.033, 2.982]}>
                      <mesh
                        name="Cube_0_Mat1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube_0_Mat1_0.geometry}
                        material={materials['Mat.1']}
                      />
                    </group>
                    <group
                      name="Sphere_1"
                      position={[2.496, 8.333, -4.322]}
                      rotation={[1.267, 0.478, 2.893]}
                      scale={2.405}>
                      <mesh
                        name="Sphere_1__0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Sphere_1__0.geometry}
                        material={materials.Sphere_1__0}
                      />
                    </group>
                    <group
                      name="Cube_2"
                      position={[-2.496, 16.667, -4.322]}
                      rotation={[1.875, 0.478, 2.578]}
                      scale={3.81}>
                      <mesh
                        name="Cube_2_Mat1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube_2_Mat1_0.geometry}
                        material={materials['Mat.1']}
                      />
                    </group>
                    <group
                      name="Sphere_3"
                      position={[-5, 25, 0]}
                      rotation={[2.131, 0, 2.499]}
                      scale={5.215}>
                      <mesh
                        name="Sphere_3__0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Sphere_3__0.geometry}
                        material={materials.Sphere_1__0}
                      />
                    </group>
                    <group
                      name="Cube_4"
                      position={[-2.496, 33.333, 4.322]}
                      rotation={[1.875, -0.478, 2.418]}
                      scale={6.62}>
                      <mesh
                        name="Cube_4_Mat1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube_4_Mat1_0.geometry}
                        material={materials['Mat.1']}
                      />
                    </group>
                    <group
                      name="Sphere_5"
                      position={[2.496, 41.667, 4.322]}
                      rotation={[1.267, -0.478, 2.101]}
                      scale={8.025}>
                      <mesh
                        name="Sphere_5__0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Sphere_5__0.geometry}
                        material={materials.Sphere_1__0}
                      />
                    </group>
                    <group
                      name="Cube_6"
                      position={[5, 50, 0]}
                      rotation={[1.011, 0, 2.016]}
                      scale={9.009}>
                      <mesh
                        name="Cube_6_Mat1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube_6_Mat1_0.geometry}
                        material={materials['Mat.1']}
                      />
                    </group>
                    <group
                      name="Sphere_7"
                      position={[2.496, 58.333, -4.322]}
                      rotation={[1.267, 0.478, 1.939]}
                      scale={8.025}>
                      <mesh
                        name="Sphere_7__0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Sphere_7__0.geometry}
                        material={materials.Sphere_1__0}
                      />
                    </group>
                    <group
                      name="Cube_8"
                      position={[-2.496, 66.667, -4.322]}
                      rotation={[1.875, 0.478, 1.627]}
                      scale={6.62}>
                      <mesh
                        name="Cube_8_Mat1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube_8_Mat1_0.geometry}
                        material={materials['Mat.1']}
                      />
                    </group>
                    <group
                      name="Sphere_9"
                      position={[-5, 75, 0]}
                      rotation={[2.131, 0, 1.535]}
                      scale={5.215}>
                      <mesh
                        name="Sphere_9__0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Sphere_9__0.geometry}
                        material={materials.Sphere_1__0}
                      />
                    </group>
                    <group
                      name="Cube_10"
                      position={[-2.496, 83.333, 4.322]}
                      rotation={[1.875, -0.478, 1.456]}
                      scale={3.81}>
                      <mesh
                        name="Cube_10_Mat1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube_10_Mat1_0.geometry}
                        material={materials['Mat.1']}
                      />
                    </group>
                    <group
                      name="Sphere_11"
                      position={[2.496, 91.667, 4.323]}
                      rotation={[1.267, -0.478, 1.152]}
                      scale={2.405}>
                      <mesh
                        name="Sphere_11__0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Sphere_11__0.geometry}
                        material={materials.Sphere_1__0}
                      />
                    </group>
                  </group>
                </group>
                <group name="Cube_helix_01">
                  <group name="Cloner_2">
                    <group name="Sphere_0" position={[5, 0, 0]} rotation={[1.011, 0.033, 2.982]}>
                      <mesh
                        name="Sphere_0__0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Sphere_0__0.geometry}
                        material={materials.Sphere_1__0}
                      />
                    </group>
                    <group
                      name="Cube_1"
                      position={[2.496, 8.333, -4.322]}
                      rotation={[1.267, 0.478, 2.893]}
                      scale={2.405}>
                      <mesh
                        name="Cube_1_Mat1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube_1_Mat1_0.geometry}
                        material={materials['Mat.1']}
                      />
                    </group>
                    <group
                      name="Sphere_2"
                      position={[-2.496, 16.667, -4.322]}
                      rotation={[1.875, 0.478, 2.578]}
                      scale={3.81}>
                      <mesh
                        name="Sphere_2__0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Sphere_2__0.geometry}
                        material={materials.Sphere_1__0}
                      />
                    </group>
                    <group
                      name="Cube_3"
                      position={[-5, 25, 0]}
                      rotation={[2.131, 0, 2.499]}
                      scale={5.215}>
                      <mesh
                        name="Cube_3_Mat1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube_3_Mat1_0.geometry}
                        material={materials['Mat.1']}
                      />
                    </group>
                    <group
                      name="Sphere_4"
                      position={[-2.496, 33.333, 4.322]}
                      rotation={[1.875, -0.478, 2.418]}
                      scale={6.62}>
                      <mesh
                        name="Sphere_4__0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Sphere_4__0.geometry}
                        material={materials.Sphere_1__0}
                      />
                    </group>
                    <group
                      name="Cube_5"
                      position={[2.496, 41.667, 4.322]}
                      rotation={[1.267, -0.478, 2.101]}
                      scale={8.025}>
                      <mesh
                        name="Cube_5_Mat1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube_5_Mat1_0.geometry}
                        material={materials['Mat.1']}
                      />
                    </group>
                    <group
                      name="Sphere_6"
                      position={[5, 50, 0]}
                      rotation={[1.011, 0, 2.016]}
                      scale={9.009}>
                      <mesh
                        name="Sphere_6__0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Sphere_6__0.geometry}
                        material={materials.Sphere_1__0}
                      />
                    </group>
                    <group
                      name="Cube_7"
                      position={[2.496, 58.333, -4.322]}
                      rotation={[1.267, 0.478, 1.939]}
                      scale={8.025}>
                      <mesh
                        name="Cube_7_Mat1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube_7_Mat1_0.geometry}
                        material={materials['Mat.1']}
                      />
                    </group>
                    <group
                      name="Sphere_8"
                      position={[-2.496, 66.667, -4.322]}
                      rotation={[1.875, 0.478, 1.627]}
                      scale={6.62}>
                      <mesh
                        name="Sphere_8__0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Sphere_8__0.geometry}
                        material={materials.Sphere_1__0}
                      />
                    </group>
                    <group
                      name="Cube_9"
                      position={[-5, 75, 0]}
                      rotation={[2.131, 0, 1.535]}
                      scale={5.215}>
                      <mesh
                        name="Cube_9_Mat1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube_9_Mat1_0.geometry}
                        material={materials['Mat.1']}
                      />
                    </group>
                    <group
                      name="Sphere_10"
                      position={[-2.496, 83.333, 4.322]}
                      rotation={[1.875, -0.478, 1.456]}
                      scale={3.81}>
                      <mesh
                        name="Sphere_10__0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Sphere_10__0.geometry}
                        material={materials.Sphere_1__0}
                      />
                    </group>
                    <group
                      name="Cube_11"
                      position={[2.496, 91.667, 4.323]}
                      rotation={[1.267, -0.478, 1.152]}
                      scale={2.405}>
                      <mesh
                        name="Cube_11_Mat1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube_11_Mat1_0.geometry}
                        material={materials['Mat.1']}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3D/opera_one_-_spiral_cubes.glb')